name: build-and-push-image
on:
  push:
    branches:
      - DO-338-timescaledb-plugin
jobs:
  cancel_running_workflows:
    name: Cancel running workflows
    runs-on: ubuntu-20.04
    steps:
      - name: cancel running workflows
        uses: styfle/cancel-workflow-action@0.8.0
        with:
          access_token: ${{ github.token }}
  build-publish-docker:
    runs-on: ubuntu-latest
    name: "Build and publish Docker image"
    steps:
      - uses: actions/checkout@v1
        with:
          fetch-depth: 0
      - name: Login to GCR
        uses: docker/login-action@v1
        with:
          registry: eu.gcr.io
          username: _json_key
          password: ${{ secrets.GCR_EU_DEV_JSON_KEY }}
      - name: Docker build and push timescaledb loucust plugin
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          tags: |
            eu.gcr.io/dev-container-repo/radixdlt-locust-timescale:latest
          push: true
          context: ../../locust_plugins/timescale/locust-timescale
 